### PR TITLE
Circuit breaker tripped fn

### PR DESCRIPTION
**Pull request by tanzoniteblack**
Extend the library to be able to specify what to do when a circuit is already tripped.

### CODE REVIEW

**Comment by josephwilk** [comment]
Thanks @tanzoniteblack.

One question, is the norm with Midge now to use *_test.clj?

Digging through Midje's source code I still see the old t_*.clj test filename.

https://github.com/marick/Midje/tree/master/test/midje

**Comment by tanzoniteblack** [comment]
I don't know particularly if it's the norm with Midje to use `*_test.clj`, but I had thought it had at least become the general convention for Clojure in general and while some projects seem to use it ( https://github.com/http-kit/http-kit/tree/master/test/org/httpkit ) others, like Midje and https://github.com/ring-clojure/ring/tree/master/ring-core/test/ring/util/test seem to use other conventions.

Before looking into it, I had thought it was the de facto convention, and is the only one supported by https://github.com/bbatsov/projectile for jumping between tests and the original code, which is why I changed it, but I can change it back if you want.

**Comment by josephwilk** [comment]
I'm happy with _test. Lets try it and see if it elicits further comment.

Thanks for the pointer to https://github.com/bbatsov/projectile also!

Joe

**Comment by Leonidas-from-XIV** [comment]
Could you please release a version with this change? I think it is a very useful feature to be able to distinguish between a regular `nil` value from the underlying code or a tripped circuit.

**Pull request merged**
